### ISSUE TITLE
cpe_bluetooth.rb

### ISSUE THREAD

**Issue by cgerke** [facebook/IT-CPE#49]
This is creating a profile that modifies the /Users/_<USERNAME>_/Library/Preferences/com.apple.Bluetooth.plist keys... but the actual keys that the UI modifies are /Library/Preferences/com.apple.Bluetooth.plist

Does this cookbook actually work for you guys on El-Capitan?

**Comment by nmcspadden** [comment]
No, this creates a profile that modifies the com.apple.Bluetooth preference domain. That's how profiles work. This does not modify any of the plists on disk (at least, not directly).  Yes, this has been working on El Capitan for a while.

I wouldn't look at any of the plists while trying to determine whether or not a profile is working, because forced profiles do not write their preferences to disk.  

https://github.com/facebook/IT-CPE/blob/master/chef/cookbooks/cpe_bluetooth/resources/cpe_bluetooth.rb#L23-L52
